# Este arquivo gera a matriz GitHub Actions.
#
# Para combinações simples de tabuleiro + escudo, adicione-os aos conjuntos de tabuleiro e escudo de nível superior;
#   para obter mais controle, adicione combinações individuais de tabuleiro + escudo.
#
# para a propriedade `include`. Você também pode usar a propriedade `cmake-args`;
#   para passar sinalizadores para o comando build e `artifact-name` para atribuir um nome para distinguir as saídas do build umas das outras:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]

---
include:
  - board: nice_nano_v2
    shield: torus_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: torus_right
  - board: nice_nano_v2
    shield: settings_reset